name: gpu
channels:
  - rapidsai
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - cudf=25.02
  - cuml=25.02
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - numpy
  - pandas
  - scikit-learn
  - xarray
  - netcdf4
  - h5netcdf
  - matplotlib
  - seaborn
  - tqdm
  - jupyterlab
  - pip
  - python-dotenv
  - pip:
      - cupy-cuda12x
